keys:
  - &leona EB5CEED62922C6050F9FC85BD5B08ADFC75E3605
  - &ember 6E10217E3187069E057DF5ABE0262A773B824745
  - &martian age1jvn978zuhm52f62dqluvt9nms73tppnevjnza5v8qugjuugqzpyqhuyswa
creation_rules:
  # hosts
  - path_regex: secrets/hosts/martian.yaml
    key_groups:
      - pgp:
          - *leona
          - *ember
        age:
          - *martian
  # services
  - path_regex: secrets/services/dns-knot.yaml
    key_groups:
      - pgp:
          - *leona
          - *ember
        age:
          - *martian
  - path_regex: secrets/services/fdg-app.yaml
    key_groups:
      - pgp:
          - *leona
          - *ember
        age:
          - *martian


