keys:
  - &leona EB5CEED62922C6050F9FC85BD5B08ADFC75E3605
  - &ember 6E10217E3187069E057DF5ABE0262A773B824745
  - &martian age1jvn978zuhm52f62dqluvt9nms73tppnevjnza5v8qugjuugqzpyqhuyswa
  - &franzbroetchen age18va0t24arar7tdqlevq4awcg7hgmzgy54eu7n4hcse3vpt55gvvs9h6r0e
  - &merkur age18t0emrzdqew4glju9qhcelkvyx28ykfppg46qz6pfs866tlueapq852eg5
creation_rules:
  # hosts
  - path_regex: secrets/hosts/martian.yaml
    key_groups:
      - pgp:
          - *leona
          - *ember
        age:
          - *martian
  - path_regex: secrets/hosts/franzbroetchen.yaml
    key_groups:
      - pgp:
          - *leona
          - *ember
        age:
          - *franzbroetchen
  - path_regex: secrets/hosts/merkur.yaml
    key_groups:
      - pgp:
          - *leona
          - *ember
        age:
          - *merkur
  # services
  - path_regex: secrets/services/dns-knot.yaml
    key_groups:
      - pgp:
          - *leona
          - *ember
        age:
          - *martian
  - path_regex: secrets/services/fdg-app.yaml
    key_groups:
      - pgp:
          - *leona
          - *ember
        age:
          - *martian
          - *franzbroetchen
          - *merkur
